### ISSUE TITLE
Installation on Mac troublesome 

### ISSUE THREAD

**Issue by Dynnammo** [python-poetry/install.python-poetry.org#54] opened 2022-10-03 06:56 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
I used a Linux machine based on Arch, and everything went well during the installation process.

Since lots of my colleagues work on Mac, using the `curl` method failed for different reasons. However, going through Homebrew worked fine. It would be great to have it in the installation process for Mac (like a `Install with brew` section as instance)

**Comment by neersighted** [comment] 2022-10-03 06:59
Most likely a duplicate of #24, but you haven't provided any details.

Regarding Homebrew, the Poetry team cannot provide support for Homebrew-based installations. Downstream packages are out of the scope of the project and may patch Poetry or make decisions that affect the functionality of Poetry (e.g. Python packaging in Debian-based distros).

The only (upstream) supported installation methods are the ones documented.

**Closed by neersighted** 2022-10-03 06:59 UTC
Labels: duplicate
